name: Code Review with ChatGPT
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: ChatGTP explain code
    steps:
      - name: ChatGTP explains
        uses: crnvl96/gh-gpt-integration-node@1.0.13
        with:
          openai_api_key: ${{ secrets.openai_api_key }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_pr_id: ${{github.event.pull_request.number}}