on:
  pull_request:
    types: [opened, synchronize]
jobs:
  code_review:
    runs-on: ubuntu-latest
    name: AI code review
    steps:
      - name: ChatGTP explains
        uses: crnvl96/gh-gpt-integration-node@1.0.21
        with:
          openai_api_key: ${{ secrets.openai_api_key }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_pr_id: ${{ github.event.number }}