name: Code Review with ChatGPT
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: ChatGTP explain code
    steps:
      - uses: actions/checkout@v2
      - name: Run script file
        run: |
          chmod +x ../main.sh
          ../main.sh
      shell: bash