name: Code Review with ChatGPT
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: ChatGTP explain code
    steps:
      - uses: actions/checkout@v2
      - run: chmod +x ../main.sh
      - run: ../main.sh
      shell: bash